# Generated by Django 4.1.7 on 2023-03-11 15:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='Year',
            new_name='year',
        ),
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='gallery'),
            preserve_default=False,
        ),
    ]
